---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.16.4

platforms:
  - name: debian
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: debian-7-chef
      box_url: http://bit.ly/dsi-debian-7-box
      network:
        - ['private_network', {ip: '172.28.128.3'}]
      customize:
        memory: 2048
        cpus: 2

provisioner:
  name: chef_solo

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[apt::default]
      - recipe[redmine::database]
      - recipe[redmine::apps]
    attributes:
      redmine:
        version: '2.6.1'
        language: 'fr'
        domain_name: 'redmine.dev'
        mysql_root_pw: 'password'
        apps: 'redmine'
        admin: 'redmine'
        password: 'password'
        db_server: 'localhost'
        apps_server: 'localhost'
        group: 'redmine'
