name 'redmine'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures redmine'
long_description 'Installs/Configures redmine'
version '0.1.0'
